const STORAGE_KEYS={slots:"planningFaq_slots_outlook_v1",faq:"planningFaq_faq_outlook_v1",structures:"planningFaq_structures_outlook_v1"};
const DEFAULT_STRUCTURES=[{id:"europe",name:"Europe",color:"#2563eb"},{id:"artois-champagne",name:"Artois Champagne",color:"#f97316"},{id:"neuville",name:"Neuville",color:"#16a34a"},{id:"quentin-web",name:"Quentin Web",color:"#7c3aed"},{id:"benjamin-rouche",name:"Benjamin Rouché",color:"#db2777"},{id:"autre",name:"Autre",color:"#64748b"}];
const LOGIN_CURTAIN_DURATION=950,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let currentUser=null,slots=load(STORAGE_KEYS.slots,[]),faqItems=load(STORAGE_KEYS.faq,[]),structures=load(STORAGE_KEYS.structures,DEFAULT_STRUCTURES);
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function uid(){return crypto?.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}function minutes(t){const[h,m]=String(t).split(":").map(Number);return h*60+m}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function slug(v){return String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"structure"}function isAdmin(){return currentUser?.role==="admin"}function findStructure(x){return structures.find(s=>s.id===x||s.name===x)||{id:"autre",name:x||"Autre",color:"#64748b"}}function todayValue(){return new Date().toISOString().slice(0,10)}function formatDateFr(d){return d?new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${d}T12:00:00`)):""}function formatSlotLabel(slot){const st=findStructure(slot.structureId);return `${formatDateFr(slot.date)} · ${slot.start}–${slot.end} · ${st.name}`}
function init(){$("#login-form").addEventListener("submit",onLogin);$("#logout-btn").addEventListener("click",logout);$("#open-outlook-link").addEventListener("click",openOutlookCalendar);$("#slot-form").addEventListener("submit",saveSlotForm);$("#slot-cancel-edit").addEventListener("click",resetSlotForm);$("#faq-form").addEventListener("submit",saveFaqForm);$("#faq-cancel-edit").addEventListener("click",resetFaqForm);$("#faq-slot").addEventListener("change",applySelectedSlotToFaqForm);$("#export-faq").addEventListener("click",exportFaqCsv);$("#clear-demo").addEventListener("click",clearLocalData);$("#structure-form").addEventListener("submit",addStructure);$$(".tab-btn").forEach(b=>b.addEventListener("click",()=>switchTab(b.dataset.tab)));$("#slot-date").value=todayValue();$("#faq-date").value=todayValue();renderStructureOptions();renderOutlookCalendar()}
function onLogin(e){e.preventDefault();const u=$("#username").value.trim(),p=$("#password").value,user=window.APP_USERS.find(x=>x.username===u&&x.password===p);if(!user){$("#login-error").hidden=false;return}currentUser=user;$("#login-error").hidden=true;$("#user-label").textContent=`${user.name} — ${user.role==="admin"?"Administrateur":"Collègue"}`;setupRoleDisplay();renderAll();$("#app-screen").hidden=false;$("#login-screen").hidden=false;document.body.classList.add("app-ready");requestAnimationFrame(()=>$("#login-screen").classList.add("opening"));setTimeout(()=>{$("#login-screen").hidden=true},LOGIN_CURTAIN_DURATION)}
function logout(){currentUser=null;document.body.classList.remove("app-ready");$("#app-screen").hidden=true;$("#login-screen").hidden=false;$("#login-screen").classList.remove("opening");$("#login-form").reset();$("#login-error").hidden=true}
function setupRoleDisplay(){$$(".admin-only").forEach(el=>el.hidden=!isAdmin());if(!isAdmin()&&($("#slots").classList.contains("active")||$("#structures").classList.contains("active")))switchTab("outlook")}
function switchTab(id){if((id==="slots"||id==="structures")&&!isAdmin())id="outlook";$$(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$$(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===id));renderAll()}
function renderAll(){setupRoleDisplay();renderOutlookCalendar();renderSlots();renderFaqSlots();renderFaq();renderStructures()}
function renderOutlookCalendar(){const url=window.APP_CONFIG?.outlookCalendarUrl||"",frame=$("#outlook-frame"),wrap=$("#outlook-frame-wrapper"),empty=$("#outlook-empty");if(!url){wrap.hidden=true;empty.hidden=false;frame.removeAttribute("src");return}empty.hidden=true;wrap.hidden=false;if(frame.src!==url)frame.src=url}
function openOutlookCalendar(){const url=window.APP_CONFIG?.outlookCalendarUrl||"";if(!url)return alert("Aucun lien Outlook n'est configuré dans data/config.js");window.open(url,"_blank")}
function saveSlotForm(e){e.preventDefault();if(!isAdmin())return;const id=$("#slot-edit-id").value,date=$("#slot-date").value,start=$("#slot-start").value,end=$("#slot-end").value,structureId=$("#slot-place").value,structure=findStructure(structureId),title=$("#slot-title").value.trim()||"FAQ Numérique";if(minutes(end)<=minutes(start))return alert("L'heure de fin doit être après l'heure de début.");if(id){const before=slots.find(s=>s.id===id),after={...before,date,start,end,structureId,place:structure.name,title,updatedAt:new Date().toISOString()};slots=slots.map(s=>s.id===id?after:s);save(STORAGE_KEYS.slots,slots);notifySlotModified(before,after)}else{const newSlot={id:uid(),ownerId:currentUser.id,date,start,end,structureId,place:structure.name,title,createdAt:new Date().toISOString()};slots.push(newSlot);save(STORAGE_KEYS.slots,slots);notifySlotCreated(newSlot)}resetSlotForm();renderAll()}
function resetSlotForm(){$("#slot-edit-id").value="";$("#slot-date").value=todayValue();$("#slot-start").value="09:00";$("#slot-end").value="10:00";$("#slot-title").value="FAQ Numérique";$("#slot-cancel-edit").hidden=true}
function renderSlots(){const list=$("#slot-list"),sorted=[...slots].sort((a,b)=>`${a.date} ${a.start}`.localeCompare(`${b.date} ${b.start}`));if(!sorted.length){list.innerHTML='<p class="muted">Aucun créneau FAQ autorisé pour le moment.</p>';return}list.innerHTML=sorted.map(slot=>{const st=findStructure(slot.structureId);return `<article class="slot-card" style="--card-color:${st.color}"><div><h4>${escapeHtml(slot.title||"FAQ Numérique")}</h4><p class="muted">${escapeHtml(formatDateFr(slot.date))}</p><div class="slot-meta"><span class="tag">${slot.start}–${slot.end}</span><span class="tag">${escapeHtml(st.name)}</span></div></div>${isAdmin()?`<div class="card-actions"><button class="edit-small" data-edit-slot="${slot.id}">Modifier</button><button class="delete-small" data-delete-slot="${slot.id}">Supprimer</button></div>`:""}</article>`}).join("");list.querySelectorAll("[data-edit-slot]").forEach(b=>b.addEventListener("click",()=>editSlot(b.dataset.editSlot)));list.querySelectorAll("[data-delete-slot]").forEach(b=>b.addEventListener("click",()=>deleteSlot(b.dataset.deleteSlot)))}
function editSlot(id){const s=slots.find(x=>x.id===id);if(!s||!isAdmin())return;$("#slot-edit-id").value=s.id;$("#slot-date").value=s.date;$("#slot-start").value=s.start;$("#slot-end").value=s.end;$("#slot-place").value=s.structureId;$("#slot-title").value=s.title||"FAQ Numérique";$("#slot-cancel-edit").hidden=false;switchTab("slots")}
function deleteSlot(id){const slot=slots.find(s=>s.id===id);if(!slot||!isAdmin())return;if(!confirm("Supprimer ce créneau FAQ autorisé ?"))return;slots=slots.filter(s=>s.id!==id);save(STORAGE_KEYS.slots,slots);notifySlotDeleted(slot);renderAll()}
function renderFaqSlots(){const c=$("#available-slots"),select=$("#faq-slot"),sorted=[...slots].sort((a,b)=>`${a.date} ${a.start}`.localeCompare(`${b.date} ${b.start}`));if(!sorted.length){c.innerHTML=`<p class="info-note">Aucun créneau FAQ numérique n'a encore été créé par l'admin.</p>`;select.innerHTML='<option value="">Aucun créneau disponible</option>';return}const prev=select.value;select.innerHTML=sorted.map(s=>`<option value="${s.id}">${escapeHtml(formatSlotLabel(s))}</option>`).join("");select.value=prev&&sorted.some(s=>s.id===prev)?prev:sorted[0].id;applySelectedSlotToFaqForm();c.innerHTML=`<h4>Créneaux FAQ autorisés par l'admin</h4><div class="slot-list">${sorted.map(s=>{const st=findStructure(s.structureId);return `<article class="slot-card" style="--card-color:${st.color}"><div><h4>${escapeHtml(s.title||"FAQ Numérique")}</h4><p class="muted">${escapeHtml(formatDateFr(s.date))}</p><div class="slot-meta"><span class="tag">${s.start}–${s.end}</span><span class="tag">${escapeHtml(st.name)}</span></div></div></article>`}).join("")}</div>`}
function applySelectedSlotToFaqForm(){const slot=slots.find(s=>s.id===$("#faq-slot").value);if(!slot)return;$("#faq-date").value=slot.date;$("#faq-start").value=slot.start;$("#faq-end").value=slot.end;$("#faq-place").value=slot.structureId;$("#faq-form-error").hidden=true}
function saveFaqForm(e){e.preventDefault();const error=$("#faq-form-error");error.hidden=true;const editId=$("#faq-edit-id").value,slot=slots.find(s=>s.id===$("#faq-slot").value);if(!slot)return showFaqError("Aucun créneau FAQ autorisé sélectionné.");const date=$("#faq-date").value,start=$("#faq-start").value,end=$("#faq-end").value,structureId=$("#faq-place").value,validation=validateFaqAgainstSlot(slot,date,start,end,structureId);if(!validation.ok)return showFaqError(validation.message);const overlap=validateNoFaqOverlap(date,start,end,structureId,editId||null);if(!overlap.ok)return showFaqError(overlap.message);const structure=findStructure(structureId);if(editId){const before=faqItems.find(f=>f.id===editId);if(!before||(!isAdmin()&&before.ownerId!==currentUser.id))return;const after={...before,slotId:slot.id,date,start,end,structureId,place:structure.name,person:$("#faq-person").value.trim(),need:$("#faq-need").value.trim(),updatedAt:new Date().toISOString()};faqItems=faqItems.map(f=>f.id===editId?after:f);save(STORAGE_KEYS.faq,faqItems);notifyFaqModified(before,after,slot)}else{const newFaq={id:uid(),slotId:slot.id,ownerId:currentUser.id,date,start,end,structureId,place:structure.name,person:$("#faq-person").value.trim(),need:$("#faq-need").value.trim(),createdAt:new Date().toISOString()};faqItems.push(newFaq);save(STORAGE_KEYS.faq,faqItems);notifyFaqCreated(newFaq,slot)}resetFaqForm();renderAll()}
function showFaqError(m){$("#faq-form-error").textContent=m;$("#faq-form-error").hidden=false}
function resetFaqForm(){$("#faq-edit-id").value="";$("#faq-person").value="";$("#faq-need").value="";$("#faq-cancel-edit").hidden=true;$("#faq-form .primary-btn").textContent="Ajouter le rendez-vous";applySelectedSlotToFaqForm()}
function validateFaqAgainstSlot(slot,date,start,end,structureId){if(date!==slot.date)return{ok:false,message:`Le RDV doit être placé le ${formatDateFr(slot.date)}.`};if(structureId!==slot.structureId)return{ok:false,message:`Ce créneau est prévu à ${findStructure(slot.structureId).name}.`};if(minutes(end)<=minutes(start))return{ok:false,message:"L'heure de fin doit être après l'heure de début."};if(minutes(start)<minutes(slot.start)||minutes(end)>minutes(slot.end))return{ok:false,message:`Le rendez-vous doit rester dans le créneau autorisé : ${slot.start}–${slot.end}.`};return{ok:true,message:""}}
function findFaqOverlap(date,start,end,structureId,excludeId=null){const sm=minutes(start),em=minutes(end);return faqItems.find(i=>!(excludeId&&i.id===excludeId)&&i.date===date&&i.structureId===structureId&&sm<minutes(i.end)&&em>minutes(i.start))}
function validateNoFaqOverlap(date,start,end,structureId,excludeId=null){const c=findFaqOverlap(date,start,end,structureId,excludeId);return c?{ok:false,message:`Impossible : il existe déjà un RDV FAQ sur ce créneau (${c.start}–${c.end}, ${c.person}).`}:{ok:true,message:""}}
function renderFaq(){const list=$("#faq-list"),sorted=[...faqItems].sort((a,b)=>`${a.date} ${a.start}`.localeCompare(`${b.date} ${b.start}`));if(!sorted.length){list.innerHTML='<p class="muted">Aucun rendez-vous FAQ enregistré pour le moment.</p>';return}list.innerHTML=sorted.map(item=>{const owner=window.APP_USERS.find(u=>u.id===item.ownerId)?.name??"Utilisateur",st=findStructure(item.structureId),can=isAdmin()||currentUser.id===item.ownerId;return `<article class="faq-card" style="--card-color:${st.color}"><div><h4>${escapeHtml(item.person)}</h4><p class="muted">${escapeHtml(item.need)}</p><div class="faq-tags"><span class="tag">${escapeHtml(formatDateFr(item.date))}</span><span class="tag">${item.start}–${item.end}</span><span class="tag">${escapeHtml(st.name)}</span><span class="tag">Ajouté par ${escapeHtml(owner)}</span></div></div>${can?`<div class="faq-actions"><button class="edit-small" data-edit-faq="${item.id}">Modifier</button><button class="delete-small" data-delete-faq="${item.id}">Supprimer</button></div>`:""}</article>`}).join("");list.querySelectorAll("[data-edit-faq]").forEach(b=>b.addEventListener("click",()=>editFaq(b.dataset.editFaq)));list.querySelectorAll("[data-delete-faq]").forEach(b=>b.addEventListener("click",()=>deleteFaq(b.dataset.deleteFaq)))}
function editFaq(id){const item=faqItems.find(f=>f.id===id);if(!item||(!isAdmin()&&item.ownerId!==currentUser.id))return;$("#faq-edit-id").value=item.id;$("#faq-slot").value=item.slotId;$("#faq-date").value=item.date;$("#faq-start").value=item.start;$("#faq-end").value=item.end;$("#faq-place").value=item.structureId;$("#faq-person").value=item.person;$("#faq-need").value=item.need;$("#faq-cancel-edit").hidden=false;$("#faq-form .primary-btn").textContent="Enregistrer la modification";switchTab("faq")}
function deleteFaq(id){const item=faqItems.find(f=>f.id===id);if(!item||(!isAdmin()&&item.ownerId!==currentUser.id))return;if(!confirm("Supprimer ce rendez-vous FAQ ?"))return;faqItems=faqItems.filter(f=>f.id!==id);save(STORAGE_KEYS.faq,faqItems);notifyFaqDeleted(item);renderAll()}
function renderStructureOptions(){const options=structures.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join("");["#slot-place","#faq-place"].forEach(sel=>{const e=$(sel);if(!e)return;const p=e.value;e.innerHTML=options;if(p&&structures.some(s=>s.id===p))e.value=p})}
function addStructure(e){e.preventDefault();if(!isAdmin())return;const name=$("#structure-name").value.trim(),color=$("#structure-color").value||"#2563eb";if(!name)return;if(structures.some(s=>s.name.toLowerCase()===name.toLowerCase()))return alert("Cette structure existe déjà.");let id=slug(name),i=2;while(structures.some(s=>s.id===id))id=`${slug(name)}-${i++}`;structures.push({id,name,color});save(STORAGE_KEYS.structures,structures);e.target.reset();$("#structure-color").value="#2563eb";renderStructureOptions();renderStructures()}
function renderStructures(){const list=$("#structure-list");if(!list||!isAdmin())return;list.innerHTML=structures.map(s=>`<article class="structure-card" style="--card-color:${s.color}"><span class="color-dot"></span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.color)}</small><button class="delete-small" data-delete-structure="${s.id}">Supprimer</button></article>`).join("");list.querySelectorAll("[data-delete-structure]").forEach(b=>b.addEventListener("click",()=>deleteStructure(b.dataset.deleteStructure)))}
function deleteStructure(id){if(!isAdmin())return;const s=structures.find(x=>x.id===id);if(!s)return;if(!confirm(`Supprimer la structure "${s.name}" ? Les éléments liés passeront en "Autre".`))return;slots=slots.map(x=>x.structureId===id?{...x,structureId:"autre",place:"Autre"}:x);faqItems=faqItems.map(x=>x.structureId===id?{...x,structureId:"autre",place:"Autre"}:x);structures=structures.filter(x=>x.id!==id);if(!structures.some(x=>x.id==="autre"))structures.push({id:"autre",name:"Autre",color:"#64748b"});save(STORAGE_KEYS.structures,structures);save(STORAGE_KEYS.slots,slots);save(STORAGE_KEYS.faq,faqItems);renderStructureOptions();renderAll()}
async function sendNotificationMail(action,details){const config=window.APP_CONFIG||{};if(!config.enableMailNotification)return;const googleScriptUrl=config.googleScriptUrl||"";if(!googleScriptUrl){alert("L'action est enregistrée, mais l'envoi automatique n'est pas encore configuré. Colle l'URL Google Apps Script dans data/config.js.");return}const actor=currentUser?`${currentUser.name} (${currentUser.role==="admin"?"admin":"collègue"})`:"Utilisateur inconnu";try{await fetch(googleScriptUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,actor,subject:`[Planning FAQ] ${action}`,...details})})}catch{alert("L'action est enregistrée, mais l'envoi du mail a échoué.")}}
function notifySlotCreated(slot){const st=findStructure(slot.structureId);sendNotificationMail("Créneau FAQ autorisé créé",{owner:currentUser?.name||"Admin",date:slot.date,start:slot.start,end:slot.end,structure:st.name,title:slot.title||"FAQ Numérique",slot:formatSlotLabel(slot),afterSummary:`Créé : ${formatSlotLabel(slot)}`})}
function notifySlotModified(before,after){const st=findStructure(after.structureId);sendNotificationMail("Créneau FAQ autorisé modifié",{owner:currentUser?.name||"Admin",date:after.date,start:after.start,end:after.end,structure:st.name,title:after.title||"FAQ Numérique",slot:formatSlotLabel(after),beforeSummary:`Avant : ${formatSlotLabel(before)}`,afterSummary:`Après : ${formatSlotLabel(after)}`})}
function notifySlotDeleted(slot){const st=findStructure(slot.structureId);sendNotificationMail("Créneau FAQ autorisé supprimé",{owner:currentUser?.name||"Admin",date:slot.date,start:slot.start,end:slot.end,structure:st.name,title:slot.title||"FAQ Numérique",slot:formatSlotLabel(slot),beforeSummary:`Supprimé : ${formatSlotLabel(slot)}`})}
function notifyFaqCreated(item,slot){const owner=window.APP_USERS.find(u=>u.id===item.ownerId)?.name??"Utilisateur",st=findStructure(item.structureId);sendNotificationMail("Nouveau rendez-vous FAQ numérique",{owner,date:item.date,start:item.start,end:item.end,structure:st.name,person:item.person,need:item.need,slot:formatSlotLabel(slot)})}
function notifyFaqModified(before,after,slot){const owner=window.APP_USERS.find(u=>u.id===after.ownerId)?.name??"Utilisateur",st=findStructure(after.structureId);sendNotificationMail("Rendez-vous FAQ numérique modifié",{owner,date:after.date,start:after.start,end:after.end,structure:st.name,person:after.person,need:after.need,slot:formatSlotLabel(slot),beforeSummary:`Avant : ${before.date} ${before.start}-${before.end} · ${before.place||""} · ${before.person||""} · ${before.need||""}`,afterSummary:`Après : ${after.date} ${after.start}-${after.end} · ${st.name} · ${after.person||""} · ${after.need||""}`})}
function notifyFaqDeleted(item){const owner=window.APP_USERS.find(u=>u.id===item.ownerId)?.name??"Utilisateur",st=findStructure(item.structureId);sendNotificationMail("Rendez-vous FAQ numérique supprimé",{owner,date:item.date,start:item.start,end:item.end,structure:st.name,person:item.person,need:item.need,beforeSummary:`RDV supprimé : ${item.date} ${item.start}-${item.end} · ${st.name} · ${item.person||""} · ${item.need||""}`})}
function exportFaqCsv(){const rows=[["date","debut","fin","structure","nom","demande","ajoute_par"].join(";")];faqItems.forEach(item=>{const owner=window.APP_USERS.find(u=>u.id===item.ownerId)?.name??"Utilisateur";rows.push([item.date,item.start,item.end,findStructure(item.structureId).name,item.person,item.need,owner].map(csvCell).join(";"))});const blob=new Blob(["\ufeff"+rows.join("\n")],{type:"text/csv;charset=utf-8"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="faq-numerique.csv";link.click();URL.revokeObjectURL(link.href)}
function csvCell(v){return `"${String(v).replaceAll('"','""')}"`}
function clearLocalData(){if(!confirm("Cela va vider les créneaux FAQ et les rendez-vous enregistrés sur ce navigateur. Continuer ?"))return;slots=[];faqItems=[];save(STORAGE_KEYS.slots,slots);save(STORAGE_KEYS.faq,faqItems);renderAll()}
init();
